import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        border: "var(--border)",
        primary: {
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
        },
        emerald: {
          50: "var(--color-emerald-50)",
          100: "var(--color-emerald-100)",
          200: "var(--color-emerald-200)",
          300: "var(--color-emerald-300)",
          400: "var(--color-emerald-400)",
          500: "var(--color-emerald-500)",
          600: "var(--color-emerald-600)",
          700: "var(--color-emerald-700)",
          800: "var(--color-emerald-800)",
          900: "var(--color-emerald-900)",
          950: "var(--color-emerald-950)",
        },
        "gray-cold": {
          50: "var(--color-gray-cold-50)",
          100: "var(--color-gray-cold-100)",
          200: "var(--color-gray-cold-200)",
          300: "var(--color-gray-cold-300)",
          400: "var(--color-gray-cold-400)",
          500: "var(--color-gray-cold-500)",
          600: "var(--color-gray-cold-600)",
          700: "var(--color-gray-cold-700)",
          800: "var(--color-gray-cold-800)",
          900: "var(--color-gray-cold-900)",
          950: "var(--color-gray-cold-950)",
        },
        "gray-warm": {
          50: "var(--color-gray-warm-50)",
          100: "var(--color-gray-warm-100)",
          200: "var(--color-gray-warm-200)",
          300: "var(--color-gray-warm-300)",
          400: "var(--color-gray-warm-400)",
          500: "var(--color-gray-warm-500)",
          600: "var(--color-gray-warm-600)",
          700: "var(--color-gray-warm-700)",
          800: "var(--color-gray-warm-800)",
          900: "var(--color-gray-warm-900)",
          950: "var(--color-gray-warm-950)",
        },
        green: {
          50: "var(--color-green-50)",
          100: "var(--color-green-100)",
          200: "var(--color-green-200)",
          300: "var(--color-green-300)",
          400: "var(--color-green-400)",
          500: "var(--color-green-500)",
          600: "var(--color-green-600)",
          700: "var(--color-green-700)",
          800: "var(--color-green-800)",
          900: "var(--color-green-900)",
          950: "var(--color-green-950)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
        "5xl": "var(--text-5xl)",
        "6xl": "var(--text-6xl)",
        "7xl": "var(--text-7xl)",
      },
      animation: {
        "pulse-custom": "pulse-custom 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        wiggle: "wiggle 1s ease-in-out infinite",
        "slide-up": "slide-up 0.3s ease-out",
        "slide-down": "slide-down 0.3s ease-out",
        "slide-left": "slide-left 0.3s ease-out",
        "slide-right": "slide-right 0.3s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        spring: "spring 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
      },
      keyframes: {
        "pulse-custom": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: ".8" },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        "slide-up": {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-down": {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-left": {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "slide-right": {
          "0%": { transform: "translateX(-100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-out": {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        spring: {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "50%": { transform: "scale(1.1)", opacity: "0.8" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;